# The sequence of triangle numbers is generated by adding 
#the natural numbers. 
#So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
#The first ten terms would be:

 #1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

#Let us list the factors of the first seven triangle numbers:

# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over
#  five hundred divisors?
import numpy as np

i = 3
n = 1
num_factors = 1
while num_factors < 500:
    n = sum(range(1,i))
    upper_limit = int((n+1)**0.5)
    possible_factors = range(1,upper_limit)
    r = np.mod(n,possible_factors) #the remainder array
    num_factors = len(r[r == 0]) #remainders of 0 indicate a factor
    i += 1

print n

